# -*- coding: utf-8 -*-
# @Time    : 2023/3/6 15:49
# @Author  : wangchuan7
# @FileName: new.py
# @Software: PyCharm
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
print ("test.pt.xiaomi.com")
print ("test.pt.xiaomi.com.jira.n.xiaomi.com")
print ("test.pt.xiaomi.com.wiki.n.miui.com")
print ("xmservice")
print ("nani.testrail.p.mi.com")